use std::path::{Path, PathBuf};
use std::sync::Arc;

use application::ports::media_repository::MediaRepository;
use domain::error::DomainError;
use domain::media::{MediaAsset, MediaOrigin};
use tracing::{debug, error, info, trace};
use walkdir::WalkDir;

use crate::importer::{compute_blake3_hash, extract_metadata};

const SUPPORTED_EXTENSIONS: &[&str] = &["mp3", "flac", "ogg", "wav", "aac", "m4a", "opus"];

#[derive(Debug, Clone)]
pub struct ScanReport {
    pub total: usize,
    pub new: usize,
    pub skipped: usize,
    pub errors: usize,
}

impl std::fmt::Display for ScanReport {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Scanned {} files. {} new, {} skipped, {} errors.",
            self.total, self.new, self.skipped, self.errors
        )
    }
}

pub struct MediaScanner {
    media_root: PathBuf,
    repo: Arc<dyn MediaRepository>,
}

impl MediaScanner {
    pub fn new(media_root: impl Into<PathBuf>, repo: Arc<dyn MediaRepository>) -> Self {
        Self {
            media_root: media_root.into(),
            repo,
        }
    }

    pub async fn scan(&self) -> Result<ScanReport, DomainError> {
        let root = &self.media_root;
        if !root.exists() {
            return Err(DomainError::NotFound(format!(
                "Media root does not exist: {}",
                root.display()
            )));
        }

        info!(path = %root.display(), "Starting media scan");

        let mut total = 0usize;
        let mut new = 0usize;
        let mut skipped = 0usize;
        let mut errors = 0usize;

        // Collect paths synchronously (walkdir is not async)
        let paths: Vec<PathBuf> = WalkDir::new(root)
            .follow_links(false)
            .into_iter()
            .filter_map(|entry| entry.ok())
            .filter(|entry| entry.file_type().is_file())
            .filter(|entry| {
                entry
                    .path()
                    .extension()
                    .and_then(|ext| ext.to_str())
                    .map(|ext| SUPPORTED_EXTENSIONS.contains(&ext.to_lowercase().as_str()))
                    .unwrap_or(false)
            })
            .map(|entry| entry.into_path())
            .collect();

        for path in paths {
            total += 1;

            match self.process_file(&path).await {
                Ok(true) => new += 1,
                Ok(false) => {
                    trace!(file = %path.display(), "Already known, skipping");
                    skipped += 1;
                }
                Err(e) => {
                    error!(file = %path.display(), error = %e, "Failed to process file");
                    errors += 1;
                }
            }
        }

        let report = ScanReport { total, new, skipped, errors };
        info!(%report, "Media scan complete");
        Ok(report)
    }

    /// Process a single file. Returns `true` if a new asset was created, `false` if skipped.
    async fn process_file(&self, path: &Path) -> Result<bool, DomainError> {
        let content_hash = compute_blake3_hash(path)
            .await
            .map_err(|e| DomainError::InvalidState(format!("Hash failed for {}: {e}", path.display())))?;

        // Dedup check
        if self.repo.find_by_content_hash(&content_hash).await?.is_some() {
            return Ok(false);
        }

        // Extract metadata using symphonia + filename fallback
        // All text fields are NFC-normalized by the importer
        let metadata = extract_metadata(path);

        let abs_path = std::fs::canonicalize(path)
            .unwrap_or_else(|_| path.to_path_buf())
            .to_string_lossy()
            .to_string();

        let asset = MediaAsset {
            id: uuid::Uuid::new_v4(),
            title: metadata.title,
            artist: metadata.artist,
            origin: MediaOrigin::LocalManaged { rel_path: abs_path },
            duration_ms: metadata.duration_ms,
            content_hash: Some(content_hash),
            original_filename: Some(metadata.original_filename),
            search_text: None, // generated by DB
        };

        debug!(id = %asset.id, title = %asset.title, artist = ?asset.artist, "Registering new media asset");
        self.repo.save(&asset).await?;
        Ok(true)
    }
}
